{
 "title": "Power",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "kWh Δ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_kwh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "youless" }
     ]
    }
   ]
  },
  {
   "title": "Current from net",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 14, "x": 5, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_watt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "youless" }
     ]
    }
   ]
  },
  {
   "title": "kWh",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_kwh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "youless" }
     ]
    }
   ]
  },
  {
   "title": "Solar kWh Δ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "watth",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_kwh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Solar kWh",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_kwh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Inverter efficiency",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_efficiency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Current from solar",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 14, "x": 5, "y": 6 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_watt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Temperature inverter",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current_temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Actual power use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "current_watt",
     "query": "SELECT sum(\"value\") / 10 FROM \"current_watt\" WHERE $timeFilter GROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}